### ISSUE TITLE
Firefox advanced settings

### ISSUE THREAD

**Issue by heyanyu** [wtetsu/mouse-dictionary#38]
Hi, lots of love for this add-on. 

1. I've noticed in https://github.com/wtetsu/mouse-dictionary/wiki/Advanced-features Chrome users could have shortcut set. Is there a way I can do that while in Firefox?

2. I've got a EN-JA default dictionary built-in, and somehow import Webster here (https://github.com/matthewreagan/WebstersEnglishDictionary), I'm not sure the priorities of them two. Mostly the Webster is shown but I still get EN-JA dictionary shown some time. Where can I set their priorities, or say, edit the current local dictionary data?

**Comment by wtetsu** [comment]
Hi, thank you for using.


1.
Yes.
about:addons -> click cogwheel -> Manage Extension Shortcuts

2.
Mouse Dictionary's internal data is very simple.
If newly import data include words that collide with existing words,
Mouse Dictionary just replaces old data with new data.

But existing words that are not included in newly imported data, the old data stays alive.

In conclusion, if you don't need the default EN-JA data,

1. Remove the Mouse Dictionary and re-install it
1. Open the options screen(cancel the confirmation dialog to install the default data)
1. Import your favorite dictionary data

Unfortunately, Mouse Dictionary doesn't have data deleting feature due to Chrome Extension limitation(deleing a lot of data takes forever, so I've removed the "delete data" button for the moment)

**Comment by heyanyu** [comment]
Finely explained. Thank you!
