### ISSUE TITLE
iOS can execute Mouse Dictionary?

### ISSUE THREAD

**Issue by jahad9819jjj** [wtetsu/mouse-dictionary#41]
From this(https://qiita.com/shiraki_s/items/d2c1a61c7db874173e69), we may run Mouse Dictionary on iOS.
But in the case of the article, the author coded the Extension. So he may understand the technology of the Extension and he can run the script.
I just would like to hear if you know if the Mouse Dictionary is in principle possible to run on iOS as in the article above.

**Comment by wtetsu** [comment]
@jahad9819jjj 

In conclusion, 

* Invoke Mouse Dictionary on iOS -> possible(maybe)
* Make Mouse Dictionary work appropriately -> difficult


I haven't tried the way you showed, but I think it's possible to "invoke" Mouse Dictionary code and display its window on iOS.

But I think the biggest obstacle for making it "work appropriately" is lacking a practical way to prepare Mouse Dictionary's internal dictionary data. 

As browser extension, Mouse Dictionary has roughly two functions.

1. Load dictionary data
2. Open Mouse Dictionary and look up the dictionary data

The 1 takes time and could consume CPU and memory, but users have to do it basically only one time. And storage for browser extension can store the data, and it won't be cleared unless Mouse Dictionary is uninstalled.


And let's back to the way you showed. As far as I read the article, JavaScript code runs on a certain webpage just as normal JavaScript code. That means, the code cannot access dictionary data that is stored in the extension storage.

In order to make Mouse Dictionary work, a certain kind of storage is required. IndexedDB or WebStorage maybe work as the alternative of extension storage, but it's not practical at all if it starts loading dictionary data every time after the user invokes Mouse Dictionary.

**Comment by jahad9819jjj** [comment]
Thank you for the detailed explanation. I'm going to try to do nothing but note taking on my iPad.

Thank you for developing a groundbreaking extension called MouseDictionary.
