### ISSUE TITLE
PDF support

### ISSUE THREAD

**Issue by wtetsu** [wtetsu/mouse-dictionary#45]
Add PDF support

**Comment by wtetsu** [comment]
![pdf_demo](https://user-images.githubusercontent.com/515948/89751418-f1234d80-db0a-11ea-8679-13c50408c06a.gif)

**Comment by monado3** [comment]
Thank you for the new feature.
But this has two problems.

# Problem 1
The pdf viewer launced by Mouse Dictionary is incomplete.
Some pdf files are not correctly rendered like [this pdf](http://www.gakkai.ne.jp/jses/pdf/pdf.pdf)
You can see some parts of a pdf are unseen.
|chrome default viewer|the viewer launched by Mouse Dictionary|
|----|----|
|<img width="664" alt="original" src="https://user-images.githubusercontent.com/36162674/90314716-d6106d80-df50-11ea-9010-5db8f4301692.png">|<img width="692" alt="after" src="https://user-images.githubusercontent.com/36162674/90314720-ddd01200-df50-11ea-99d9-a8c16567d71c.png">|

# Problem 2
On [my tool](https://github.com/monado3/pdfjs-broker), you could use Mouse dictionary until this update, by hosting pdf files by pdfjs on Docker.
Though, after this update, when you open a pdf file by my tool and then launch Mouse Dictionary, you are forced to launch the new pdf viewer and it cannnot load the pdf file somehow.

This is the screenshot at the moment that the pdf viewer failed to open the pdf viewer.
<img width="529" alt="notwork" src="https://user-images.githubusercontent.com/36162674/90314870-eecd5300-df51-11ea-96f7-ad4e6fb01d1b.png">
(Please see the bottom part of the screenshot)

# My wish
For me, I would be very glad if you can turn ON/OFF the new external pdf viewer feature.
Some people would like this update.
But other people like me don't need this feature.

I can write a Japanese version comment, if you wish because my English is too bad to read.
Thank you for reading.

**Comment by wtetsu** [comment]
@monado3 

thank you for your report


## Problem 1

Reproduced. Let me check in details later on.


## Problem 2

Could you please try changing `PDF URL pattern` in Advanced settings?
To empty this field may your tool avaiable again.

![image](https://user-images.githubusercontent.com/515948/90315264-ffcb9380-df54-11ea-89a7-e869974e3816.png)

(FYI: The function that determins PDF document or not)
https://github.com/wtetsu/mouse-dictionary/blob/master/src/main/core/start.js#L70

**Comment by monado3** [comment]
Thank you for your prompt response.

Making the field empty solution worked well.
Thank you so much for the information.

Again, thank you for this wonderful tool.

**Comment by wtetsu** [comment]
By the way, "PDF URL pattern" was an experimantal feature,
but it turned out it could cause problems like your case,
so I decided to improve that.

You don't have to bother to change the settings next time.

----

### Current(1.4.2):

* default value: `\.(?:pdf|PDF)\??[\w-=&~]*$`
* How MD determin PDF document or not
  * Embded PDF document exists -> true
  *  ↓false
  * "PDF URL pattern" matches the current URL -> true ※Here was your problem 
  *  ↓false
  * Others -> false

The default value could cause problem.


### Newer version

* default value: empty
* How MD determins PDF document or not
  * If "PDF URL pattern" is empty -> Embded PDF document exists -> true
  * If "PDF URL pattern" is NOT empty -> "PDF URL pattern" matched the current URL -> true

The default behavior is safer than before.

**Comment by wtetsu** [comment]
Problem 1: Fixed

|Chrome|Mouse Dictionary|
|----|----|
|<img width="664" alt="original" src="https://user-images.githubusercontent.com/515948/90334582-a1acb800-e009-11ea-8ea6-6608be90e002.png">|<img width="692" alt="after" src="https://user-images.githubusercontent.com/515948/90334587-ae311080-e009-11ea-8f1e-aa042808e80e.png">|

**Comment by kota-may478** [comment]
Thank you for your kind effort in PDF support.
I have one question about whether I can apply this feature to a PDF file uploaded on the Web as a JSP file.

I want to apply this feature to the PDF file uploaded on the below URL (I'm afraid you can't access the URL).
https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=9291317&tag=1

I have changed the advanced option like the below picture, but it was no effect.
Do you have any comments about this problem?
![AdvancedOption](https://user-images.githubusercontent.com/49606319/165229774-e5448f09-857c-4bc6-b2e1-63af0f90d9f2.PNG)

Thank you in advance!

**Comment by wtetsu** [comment]
Since I cannot access the URL I cannot confirm it. Is the URL reality a single PDF document? If the page is HTML and a PDF document is embedded, Mouse Dictionary doesn't work.

**Comment by kota-may478** [comment]
I see! The page is composed of JSP (=HTML+Javascript).
That's why I can't apply this feature to the page.

Thank you for your quick response!
