### ISSUE TITLE
Auto-open feature on specific web pages.

### ISSUE THREAD

**Issue by Slshift** [wtetsu/mouse-dictionary#56]
Hi.
I have used this extension for English to Japanese translation.
It is indispensable tool.
Thank you for your effort.

It is great if the extension open automatically when I open specific web pages. (by specification of regular expression of URL string?)
Is there any plan?

Thank you in advance.

**Comment by wtetsu** [comment]
Thank you for using and feedback.

There is no plan to implement auto-open feature,
because of Chrome extension's limitation.

Mouse Dictionary can run only by user manual operation on each web page.
In exchange for that, Mouse Dictionary has strong privilege (Full access) to read/write on the page.

![image](https://user-images.githubusercontent.com/515948/104805038-ea64d900-5814-11eb-9728-3f58951fa383.png)

In order to support auto-run feature, Mouse Dictionary have to get super strong privilege on all the URLs.
That is not good from the viewpoint of security, and perhaps Chrome Extension review process reject it.

----

Do you use keyboard shortcut?
Pushing the extension icon every time is annoying,
but I think it's almost fuss-free if you use keyboard shortcut to invoke Mouse Dictionary.

https://github.com/wtetsu/mouse-dictionary/wiki/Advanced-features

**Comment by Slshift** [comment]
Thank you for your answer. 
I understood about limitation of chrome extensions. 

And thank you for introducing keyboard shortcut.
It works very well for me.
