### ISSUE TITLE
Unreadable with dark-theme extensions

### ISSUE THREAD

**Issue by kydo** [wtetsu/mouse-dictionary#7]
Hi,

First up, thanks for your work on mouse-dictionary.
I like this super fast searchable dictionary ever I have tried :)

But I have a problem.
With extension for dark theme such as [Dark Reader](https://github.com/darkreader/darkreader), readability is really wrong for the letter-color is also black.

What about feature to change letter color on MouceDictionary? 
I'm bit busy now but after some weeks I could try to implement it by myself.

**Comment by wtetsu** [comment]
Thank you for your using Mouse Dictionary and requests!

Actually, I've been tackling designing and developing it because quite a few users have asked me about that kind of features.  I'm going to release a new version which has a better text parser and customizable user configs in a few days or so. (^^)

The new user-customizable feature will have two layers.

1: For general users
2: For power users

1 is easy to use but very limited feature.
(e.g. initial dialog size, font size, font color, and so forth)

2 requires knowledge of HTML/CSS but very flexible.
Users can modify even HTML templates.

**Comment by wtetsu** [comment]
Here is an example of customized UI I tried the feature.

![image](https://user-images.githubusercontent.com/515948/45371226-09d80f80-b625-11e8-8f7c-0287927d073f.png)

(default)
![image](https://user-images.githubusercontent.com/515948/45371201-fa58c680-b624-11e8-8a45-400bf2edc4ad.png)

**Comment by kydo** [comment]
😮✨ 
I'm so pumped about the features! 
Thanks for your response :)

**Comment by wtetsu** [comment]
http://wtetsu.hatenablog.com/entry/2018/09/17/122547

**Comment by kydo** [comment]
Thanks for your notice. This issue was resolved ✨ 
![image](https://user-images.githubusercontent.com/18145923/45664925-7ed9a680-bb49-11e8-930c-ff9a3e8e90b8.png)

**Comment by wtetsu** [comment]
Great 😄
