### ISSUE TITLE
It doesn't work in ncatlab.org.

### ISSUE THREAD

**Issue by linuxmetel** [wtetsu/mouse-dictionary#78]
This addon doesn't work in ncatlab.org.
In https://ncatlab.org/nlab/show/HomePage, I got following error message from Console tab in Firefox DevTools when I placed the cursor over a word.

```
XML Parsing Error: not well-formed
Location: 
Line Number 5, Column 107:

SyntaxError: An invalid or illegal string was specified
```

**Comment by wtetsu** [comment]
v1.6.4 will fix it (not released yet as of 2022-08-13)

Please try factory reset after updating.
https://github.com/wtetsu/mouse-dictionary/wiki/Factory-reset

**Comment by wtetsu** [comment]
v1.6.4 has been released on 2022-08-15.
Please try.

**Comment by linuxmetel** [comment]
I checked it works in Chromium. Thank you.

But I mainly use Firefox and v.1.6.x hasn't been released in [addons.mozilla.org](https://addons.mozilla.org) yet. Unfortunately, Firefox isn't supported any more?

**Comment by wtetsu** [comment]
Is Firefox just your preference?
Or do you use Mouse Dictionary in an environment where you can't use other browsers, like at work or school?

Due to Firefox extension's terrible and unreasonable review process, I don't want to update Firefox edition proactively.
They often bother me by asking strange questions and try to delete this extension. If the next time the same thing happens, Mouse Dictionary may be permanently deleted.

https://twitter.com/wtetsu/status/1521108048714289152

**Comment by linuxmetel** [comment]
Firefox is just my preferece.
I didn't know about Firefox extension's review process and I see now,

I'll try to build on my PC.

**Comment by wtetsu** [comment]
@linuxmetel 

By the way, the root cause of this issue was the default template settings.
(See 37f587f8b42e2011066649855b3fe4239f496c8b)

You don't need the latest Mouse Dictionary.
You can edit your template settings and fix it by yourself.


![image](https://user-images.githubusercontent.com/515948/185729327-02959d6b-6e07-48e1-a1a4-76bc50500e32.png)

![image](https://user-images.githubusercontent.com/515948/185729345-906a725e-004a-4c63-a4f9-1e697914497c.png)

**Comment by linuxmetel** [comment]
Thank you.
